### ISSUE TITLE
Crash on `/***`

### ISSUE THREAD

**Issue by DreierF** [hosseinmd/prettier-plugin-jsdoc#18]
Hi,

First of all thanks for this awesome plugin! It mostly works really great, but I found an edge case in our code base that makes it crash with:

```
[error] Dummy.js: TypeError: Cannot read property 'description' of undefined
[error]     at Object.convertCommentDescToDescTag (.../node_modules/prettier-plugin-jsdoc/lib/utils.js:105:17)
[error]     at .../node_modules/prettier-plugin-jsdoc/lib/parser.js:45:17
[error]     at Array.forEach (<anonymous>)
[error]     at Object.jsdocParser [as parse] (.../node_modules/prettier-plugin-jsdoc/lib/parser.js:31:18)
[error]     at Object.parse (.../node_modules/prettier/index.js:13625:19)
[error]     at coreFormat (.../node_modules/prettier/index.js:14899:14)
[error]     at format (.../node_modules/prettier/index.js:15131:14)
[error]     at Object.formatWithCursor (.../node_modules/prettier/index.js:57542:12)
[error]     at format (.../node_modules/prettier/bin-prettier.js:15883:14)
[error]     at Object.formatFiles (.../node_modules/prettier/bin-prettier.js:16067:16)
error Command failed with exit code 2.
```

Reproduction example:
```
/***
 * Some comment
 */
export class Dummy {

}
```

I'm aware that this is not a "correct" JSDoc comment as it should only have two asterisk characters, but the plugin should just ignore/remove the additional asterisk symbol.

**Comment by hosseinmd** [comment]
Fixed: https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/1ac43d16845d796c72c9cfac04da17ea739bdb03
Release: v0.2.13  https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/24428a0cd4923b824fe246cc8c9836e72b698aba

Thank you.
